"""Shared fixtures for the recount test suite.

Provides the canonical 4-leaf binary test case used to verify the NumPy and
PyTorch backends against the reference Java implementation (Count XXV).
The numerical reference values were generated by a small Java driver that
invokes count.model.Likelihood + count.model.Gradient with
`setMinimumObservedCopies(1)`.
"""
import numpy as np
import pytest

from recount import Tree, GLDRates


# ----------------------------------------------------------------------------
# tree, rates, profiles
# ----------------------------------------------------------------------------

# Newick: ((A:0.5,B:0.3):0.2,(C:0.4,D:0.6):0.1);
# Node indices (leaves first, parent index > child index):
#     0 = A, 1 = B, 2 = C, 3 = D
#     4 = (A,B), 5 = (C,D), 6 = root
PARENT = np.array([4, 4, 5, 5, 6, 6, -1])
LEAF_NAMES = ["A", "B", "C", "D"]

GAIN_RATES = np.array([0.10, 0.20, 0.15, 0.25, 0.30, 0.18, 0.50])
LOSS_RATES = np.array([1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00])
DUP_RATES = np.array([0.40, 0.30, 0.50, 0.20, 0.45, 0.35, 0.00])
EDGE_LENGTH = np.array([0.50, 0.30, 0.40, 0.60, 0.20, 0.10, np.inf])

PROFILES = np.array([
    [1, 0, 1, 1],
    [2, 0, 0, 1],
    [1, 1, 1, 1],
    [3, 2, 1, 0],
], dtype=np.int64)


@pytest.fixture
def tree() -> Tree:
    return Tree(parent=PARENT, leaf_names=LEAF_NAMES)


@pytest.fixture
def rates(tree: Tree) -> GLDRates:
    return GLDRates(
        tree=tree,
        gain=GAIN_RATES, loss=LOSS_RATES, dup=DUP_RATES, length=EDGE_LENGTH,
    )


@pytest.fixture
def profiles() -> np.ndarray:
    return PROFILES.copy()


# ----------------------------------------------------------------------------
# Java reference numbers (count.model.Gradient with min_copies=1)
# ----------------------------------------------------------------------------

# Forward log-likelihoods
JAVA_LL_RAW = -22.828057245637
JAVA_LL_CORRECTED_MIN1 = -19.549998418545
JAVA_LL_EMPTY = -0.580971740120
JAVA_LL_SINGLETON = -2.395794662445

JAVA_LL_PER_FAMILY = np.array([
    -4.718514262887,
    -7.076803097912,
    -3.678838805376,
    -7.353901079461,
])

# Corrected survival gradient (min_copies=1), indexed [node, {GAIN=0, LOSS=1, DUP=2}]
# These are ∂(ln L*)/∂(p̃, q̃, r̃/κ̃) — the orientation of Java's
# Gradient.getCorrectedGradient().
JAVA_GRADIENT_SURVIVAL = np.array([
    [ 6.474801393571e-01, -6.039058620592e+00,  6.327173214408e+00],  # node 0 (leaf A)
    [-5.832741090132e-01,  7.657675543676e+00, -3.442377009903e+00],  # node 1 (leaf B)
    [-1.235754528008e+00,  1.156682901058e+00, -4.833024979152e+00],  # node 2 (leaf C)
    [-4.693230084236e-01, -1.215266469122e+00, -4.648020383458e+00],  # node 3 (leaf D)
    [-5.109813500281e-02, -3.995406790690e+00,  3.104705710827e+00],  # node 4 (A,B)
    [-1.989540042975e-01, -6.280286100697e-01, -4.801469013416e+00],  # node 5 (C,D)
    [ 7.444742630037e-01,  0.000000000000e+00,  0.000000000000e+00],  # node 6 (root)
])

# Corrected distribution gradient (min_copies=1) — output of Java's
# Gradient.getDistributionGradient(getCorrectedGradient()), i.e. chain-ruled
# from survival params (p̃, q̃, r̃/κ̃) to raw params (p, q, κ or r). The GAIN
# column differs from the survival version at Poisson nodes (multiplied by
# (1-ε)) because r̃ = r·(1-ε); at the Pólya nodes the GAIN axis is identical.
JAVA_GRADIENT_DISTRIBUTION = np.array([
    [ 6.474801393571e-01, -6.883054343796e+00,  6.327173214408e+00],
    [-5.832741090132e-01,  6.415585104940e+00, -3.442377009903e+00],
    [-1.235754528008e+00,  9.467429468775e-01, -4.833024979152e+00],
    [-4.693230084236e-01, -1.363365847113e+00, -4.648020383458e+00],
    [-5.109813500281e-02, -3.725438802043e+00,  3.145317041517e+00],
    [-1.989540042975e-01, -6.259821321430e-01, -4.120934548844e+00],
    [ 7.059264001606e-01,  0.000000000000e+00,  0.000000000000e+00],
])


@pytest.fixture
def java_reference() -> dict:
    return {
        "ll_raw": JAVA_LL_RAW,
        "ll_corrected_min1": JAVA_LL_CORRECTED_MIN1,
        "ll_empty": JAVA_LL_EMPTY,
        "ll_singleton": JAVA_LL_SINGLETON,
        "ll_per_family": JAVA_LL_PER_FAMILY,
        "gradient_survival": JAVA_GRADIENT_SURVIVAL,
        "gradient_distribution": JAVA_GRADIENT_DISTRIBUTION,
    }
