#!/bin/bash
# hourly_checkup.sh — survives Claude session death.
#
# Runs an hourly pass that: regenerates plots for fits that have landed,
# updates README + PROGRESS + RESUME_CONTEXT with fresh LL / fm / cp /
# max_dup / max_gain, and pushes to GitHub. Designed to be a drop-in
# alternative to the in-session Claude cron — invoke with nohup +
# disown so it survives terminal close:
#
#     cd <your local clone of recount>
#     nohup tools/hourly_checkup.sh > validation/logs/hourly_checkup.log 2>&1 &
#     disown
#
# Stop with:  pkill -f hourly_checkup.sh
set -u
cd "$(dirname "$0")/.."

INTERVAL=3600  # 1 hour
LOG=validation/logs/hourly_checkup.log
mkdir -p validation/logs

log() { echo "[$(date +%H:%M:%S)] $*"; }

do_one_pass() {
  log "=== HOURLY CHECKUP ==="

  # 1. Pool snapshot
  if [ -f validation/logs/pool_master.log ]; then
    log "--- pool tail ---"
    tail -10 validation/logs/pool_master.log
  fi

  # 2. Completed fits since last hour
  log "--- saved fits inventory (post-port, mtime ≥ 16:30 today) ---"
  PYTHONPATH=. python3 - <<'PY'
import json, os, time
threshold = time.mktime(time.strptime(time.strftime("%Y-%m-%d ")+"16:30", "%Y-%m-%d %H:%M"))
for kind in ['sota_ml','map_sigma1','csuros_match']:
    for ds in ['dpann80','proteo75','eury114','ed194','williams','arc269']:
        suffix = '_sigma1.0' if kind=='map_sigma1' else ''
        p = f'validation/outputs/{kind}/{ds}{suffix}_summary.json'
        if not os.path.exists(p): continue
        mt = os.path.getmtime(p)
        if mt < threshold or time.localtime(mt).tm_yday != time.localtime().tm_yday:
            continue
        with open(p) as f: d = json.load(f)
        ll = (d.get('final') or {}).get('ll')
        fm = (d.get('final') or {}).get('root_families_corr')
        cp = (d.get('final') or {}).get('root_copies_corr')
        cbs = (d.get('csuros_baseline') or {}).get('ll')
        delta = ll-cbs if isinstance(ll,float) and isinstance(cbs,float) else None
        tstr = time.strftime('%H:%M', time.localtime(mt))
        print(f"  [{tstr}] {kind:14s}/{ds:10s}: LL={ll:.1f} fm={fm:.0f} cp={cp:.0f} Δ={delta:+.0f}" if delta else f"  [{tstr}] {kind}/{ds}: LL={ll}")
PY

  # 3. Regenerate plots
  log "--- regenerating plots ---"
  PYTHONPATH=. python3 validation/subset_only_path_plot.py 2>&1 | tail -8 || true
  # arc269-overlay plot only if at least one arc269 fit is fresh on disk:
  for f in validation/outputs/{sota_ml,map_sigma1}/arc269*.json; do
    if [ -f "$f" ] && [ "$(stat -f %m "$f" 2>/dev/null || echo 0)" -gt "$(date -j -f '%Y%m%d_%H%M' '20260518_1630' +%s)" ]; then
      log "  arc269 fresh fit detected; running subclade_ancestor_comparison.py"
      PYTHONPATH=. python3 validation/subclade_ancestor_comparison.py 2>&1 | tail -3 || true
      break
    fi
  done

  # 4. Refresh README tables from fresh saved fits
  log "--- refreshing README.md tables ---"
  PYTHONPATH=. python3 tools/refresh_readme_tables.py 2>&1 | tail -2 || true

  # 5. Stamp PROGRESS + RESUME_CONTEXT with timestamp; minimal touch
  TS=$(date "+%Y-%m-%d %H:%M JST")
  sed -i.bak "s/^> Updated: .*/> Updated: $TS (hourly auto-checkup)/" PROGRESS.md RESUME_CONTEXT.md 2>/dev/null
  rm -f PROGRESS.md.bak RESUME_CONTEXT.md.bak

  # 5. git push if anything changed
  if [ -n "$(git status --short)" ]; then
    log "--- changes detected, committing + pushing ---"
    git add -A README.md PROGRESS.md RESUME_CONTEXT.md \
                validation/outputs/*.png \
                validation/outputs/sota_ml validation/outputs/map_sigma1 \
                validation/outputs/csuros_match 2>/dev/null || true
    git commit -m "hourly checkup at $(date +%H:%M): refresh plots + state" \
               -m "Auto-generated by tools/hourly_checkup.sh." 2>&1 | tail -3 || true
    git push origin claude/goofy-heisenberg-17d13f:claude/confident-fermi-ec9e2c 2>&1 | tail -2 || true
    git push origin claude/goofy-heisenberg-17d13f:main 2>&1 | tail -2 || true
  else
    log "  no changes to commit"
  fi

  log "=== END CHECKUP — sleeping $INTERVAL s ==="
}

while true; do
  do_one_pass
  sleep $INTERVAL
done
